name: Test
run-name: Run tests ${{ github.actor }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        run: |
          cd ${{ github.workspace }}
          pytest --showlocals
      - run: echo "${{ job.status }}."

